// Vendors a fixed set of Ionicons v8.1.0 (MIT) outline glyphs into src/icons/glyphs.ts.
// Usage: node scripts/vendor-icons.mjs <path to unpacked ionicons package>
import fs from "node:fs";
const src = process.argv[2] ?? "/tmp/ion/package";
const names = { close: "close-outline", add: "add-outline", trash: "trash-outline", scan: "scan-outline", settings: "settings-outline", clipboard: "clipboard-outline", search: "search-outline", pin: "pin-outline", copy: "copy-outline", check: "checkmark-outline", edit: "create-outline", folder: "folder-outline", flash: "flash-outline", map: "map-outline", download: "download-outline", upload: "cloud-upload-outline", sun: "sunny-outline", moon: "moon-outline", chevron: "chevron-down-outline", time: "time-outline", bookmark: "bookmark-outline", cursor: "navigate-outline" };
const out = {};
for (const [k, f] of Object.entries(names)) {
  const svg = fs.readFileSync(`${src}/dist/svg/${f}.svg`, "utf8");
  out[k] = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").replace(/<title>.*?<\/title>/g, "").trim();
}
fs.writeFileSync("src/icons/glyphs.ts", `// Generated by scripts/vendor-icons.mjs from Ionicons 8.1.0 (MIT). See LICENSE-ionicons.txt.\nexport const GLYPHS = ${JSON.stringify(out, null, 1)} as const;\n`);
console.log(Object.keys(out).length, "glyphs");
